/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author User
 */
public class Movie_Maven extends javax.swing.JFrame {

    /**
     * Creates new form Movie_Maven
     */
    public Movie_Maven() {
        
        //Full Screen window
        setUndecorated(true);
        
        setAlwaysOnTop(true);
        setResizable(false);
        setVisible(true);
        Toolkit tk= Toolkit.getDefaultToolkit();
        
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        
        setSize(x,y);
//End of Full Screen window
        
       
        initComponents();
    }
    
    //close button (label)
    public void close(){
        WindowEvent closeWindow = new  WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    //end of close button (label)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jbtnOpenRegister_Customer = new javax.swing.JButton();
        jbtnOpenLoginHelpPage = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        MavenBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 390, 70));

        jbtnOpenRegister_Customer.setBackground(new java.awt.Color(0, 0, 0));
        jbtnOpenRegister_Customer.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jbtnOpenRegister_Customer.setForeground(new java.awt.Color(153, 153, 153));
        jbtnOpenRegister_Customer.setText("REGISTER");
        jbtnOpenRegister_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOpenRegister_CustomerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnOpenRegister_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 390, 70));

        jbtnOpenLoginHelpPage.setBackground(new java.awt.Color(0, 0, 0));
        jbtnOpenLoginHelpPage.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnOpenLoginHelpPage.setForeground(new java.awt.Color(153, 153, 153));
        jbtnOpenLoginHelpPage.setText("HELP");
        jbtnOpenLoginHelpPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOpenLoginHelpPageActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnOpenLoginHelpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 210, 40));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(153, 153, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 30, 30));

        MavenBG.setBackground(new java.awt.Color(0, 0, 0));
        MavenBG.setForeground(new java.awt.Color(153, 153, 153));
        MavenBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MovieMavenBG.jpg"))); // NOI18N
        MavenBG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(MavenBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Open the Login page button
        Login f2= new Login();
        f2.setVisible(true);
        
        //Hide the Current Page
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        close();
       //above is the close fuction
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnOpenLoginHelpPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOpenLoginHelpPageActionPerformed
        // Open the Login Help page button
        LoginHelpPage f2= new LoginHelpPage();
        f2.setVisible(true);
        
        //Hide the Current Page
        this.setVisible(false);
    }//GEN-LAST:event_jbtnOpenLoginHelpPageActionPerformed

    private void jbtnOpenRegister_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOpenRegister_CustomerActionPerformed
        // Open the Register_customer page button
        Register_Customer f2= new Register_Customer();
        f2.setVisible(true);
        
        //Hide the Current Page
        this.setVisible(false);
    }//GEN-LAST:event_jbtnOpenRegister_CustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movie_Maven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movie_Maven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movie_Maven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movie_Maven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movie_Maven().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MavenBG;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnOpenLoginHelpPage;
    private javax.swing.JButton jbtnOpenRegister_Customer;
    // End of variables declaration//GEN-END:variables
}
